### ISSUE TITLE
Stipend Implementation

### ISSUE THREAD

**Issue by maennchen** [erlef/phx_gen_oidcc#1]
Part of https://github.com/Erlang-Openid/oidcc/issues/221

## Requirements

* [x] Good Test Coverage
* [x] Good Code Quality
* [x] Conforms to the following [Conformance Profiles](https://openid.net/wordpress-content/uploads/2018/06/OpenID-Connect-Conformance-Profiles.pdf)
  * [x] Basic Relying Party
  * [x] Relying Party Using Configuration Information
  * [x] Form Post Relying Party
* [X]  Secure Defaults
  * [X] ~~Shipped with a secure and complete TLS setup~~ OTP 26 ships with one
  * [X] Can be overridden with custom TLS settings
  * [X] JWT Settings are automatically set up to the most strict settings according to the OIDC Config Introspection
* [x] GitHub Actions Setup that runs
  * [x] Unit Tests
  * [x] Linter
  * [x] Dialyzer
* [x] All libraries are well documented on Hex via [rebar3_ex_doc](https://hex.pm/packages/rebar3_ex_doc)
  * [x] public functions have dialyzer specs
  * [x] public functions have examples
  * [X] contains setup instructions
  * [X] contains examples for most common use cases
* [x] Compatible with latest stable OTP releases at time of publication

## TODO

* [x] Move repos to @erlef - @peerst
* [x] Public Testing
* [x] Stable Release
